### ISSUE TITLE
chore(platform): qualify iOS and macOS 27 with an OS 26 minimum

### ISSUE THREAD

**Issue by roryford** [ManifoldKit/ManifoldKit#2517]
## Why it matters

OS 27 support needs a tested platform/toolchain transition under MK's n−1 policy. Current core and examples still target iOS 18/macOS 15, and CI uses macos-15. A successful SDK build alone does not prove supported runtime behavior or existing-store safety.

## Scope and evidence — 2026-09-10

Source baseline: `78a1837efdd44cc85e730684b5772d7b8536b3ee`. Host macOS 26.6.2 (25G83); Xcode 27 beta 4 (27A5228h), Swift 6.4; iOS 27 simulator runtime 24A5380i. These are beta evidence, not September RC or GA qualification.

- Complete `swift build --build-tests --traits Server,Macros -j 6` passed under Xcode 27 beta 4. Unchanged tools-version 6.1 manifest also loads on Xcode 26.6. No observed need to raise tools-version just to compile against the newer SDK.
- `scripts/test.sh --profile local --skip-update` reported 6,223 pass / 1 fail in its first batch. The failure is `AgentsMdPlansStatusAuditTest.testNoStaleNonActivePlan`: `1997-on-device-eval.md`, `api-review-2026-07.md`, and `tested-models-cross-repo.md` reached 60 days. It is a date/history audit, not an SDK incompatibility; dispose of those plans honestly before claiming a green gate. Do not touch their dates or relabel Active merely to pass.
- The profile stopped before its remaining processes. Running the complete `ManifoldBackendsTests` target separately with Macros/parallel passed 885 tests; the complete `ManifoldInferenceSwiftTestingTests` target passed 87. These do not turn the failed full gate green. Parallel runner pass totals can include runtime skips.
- The Advanced example built and launched on the iOS27 simulator. The chat shell displayed an Apple Intelligence model-not-ready error and no model selected, while the process remained alive. This proves startup/error presentation, not working inference or complete UI qualification.
- A standalone synthetic SwiftData fixture saved 20 records via a ModelActor on iOS26.5 and reopened/validated all records on iOS27. This is framework smoke evidence only, not MK's V3–V13 migration plan or physical-device upgrade proof.
- UI source inspection found existing text-selection and environment/style seams; no FileDocument or AsyncImage use in UI/management/examples. No blanket migration for those unused APIs is justified.

## Acceptance criteria

- [ ] At general release, update core/example minimums to iOS26/macOS26 under n−1; keep OS27-only and later-26.x API guards. Coordinate companion requirements and actively maintained consumers. Do not automatically revive held/retired apps (#2155).
- [ ] Select and record actual supported Xcode/Swift/SDK/runner versions. Separate compiler compatibility, SDK availability and runtime availability. Reproduce the full local gate on the target supported toolchain and resolve the stale-plan baseline failure with truthful plan dispositions.
- [ ] Validate both OS26 and OS27 runtimes; update CI so tests cannot claim the new deployment floor while running only macOS15. Use actual available runner/runtime evidence; keep physical Foundation inference separate from simulator/hosted checks.
- [ ] Run `scripts/demo-apps-build.sh` and current companion/eval compatibility against the release source revision; record missing hardware/tooling explicitly (#2477 owns existing canary roster drift).
- [ ] Exercise streaming text selection/copy/citations/context menus, composer focus/input/cancel, session switching, endpoint and model-switcher presentations, theme propagation, accessibility and keyboard navigation on both generations. Change UI only for demonstrated regressions or intentional adoption.
- [ ] Exercise MK's full schema/migration plan using persisted prior-version stores, session/message/branch/endpoint/attachment restoration, background saves and presentation teardown. Add a schema version only for an actual schema change.
- [ ] Update AGENTS.md platform policy, readiness/toolchain docs, migration guidance and floor-change release notes. Follow the applicable advance-notice policy; OS27 current means OS26 minimum, not OS27 minimum.

## Related feature work

Image support remains #1710; model-switch budget lifetime remains #1957; llama provider remains #2436; no-op trait disposition remains #1577; positioning remains #2171. Native Foundation context/error modernization and PCC have separate feature scopes. This issue owns compatibility/qualification, not all Apple framework adoption.

## Reproduction

From an isolated checkout of the source baseline, select the recorded Xcode through DEVELOPER_DIR and run the existing build/local-gate commands above. Server adds optional dependency pins; the spike preserved all original pinned revisions. The fresh resolve used Hummingbird 2.23.0 and its graph. No production code was changed in the spike.

Primary platform references: [iOS27 release notes](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-27-release-notes), [macOS27 release notes](https://developer.apple.com/documentation/macos-release-notes/macos-27-release-notes).

## Coordination

Native Foundation modernization: #2518. Explicit PCC backend: #2519.

**Comment by roryford** [comment]
## macOS 27 physical inference evidence — 18 September 2026

Host: Apple M5 Pro, 64 GB RAM, macOS 27.0 (26A428), Xcode 27.0 (27A266a), Swift 6.4. Core production sources: `c890aa09f718dd2fb42f8e2642655298310aa70a` (PR #2529). Companions were locally bound to that core: MLX `dfdf3480e082990d9e830db10e2ab7de17b60ba6`, llama `b5d1de633324f084cb8888d2fef6e3689d6bb722`, eval `eea8e8c214f0c263a2f39eefcd3744750ee72b54`.

- Foundation regular selection: 66 passed, 3 skipped; actual system-model generation/history/guided/tool cases executed. Enabling slow contracts gave 66 passed, 2 failed, 1 skipped because participants were unloaded, now tracked in #2530. These overlapping invocations must not be summed into unique coverage.
- Ollama: 364 fuzz iterations with no findings; 216 tool-task scenario executions with failures retained in #2336. Real Gemma vision passed both cases after an identical-digest alias worked around broken discovery (#2530). Qwen normal/capped reasoning returned no visible answer; raw-wire diagnosis remains open under #2530, not an established MK regression.
- MLX: stock shader compilation failed; explicit Metal 4.0 allowed a test build (ManifoldKit/manifold-mlx#207). Under that override, 33 tests passed, 2 failed, 7 skipped; actual vision and SDXL generation passed. Existing #197/#198 failures were reproduced. Native-tool generation exceeded the intended bounded behavior (ManifoldKit/manifold-mlx#206).
- llama: the full Mistral suite was interrupted by a test subprocess deadlock (ManifoldKit/manifold-llama#205); a supplemental run excluding two CLI classes is not a green full gate. The fixed KV-reuse threshold is false for the observed tokenizer; intermittent early-EOG behavior still needs diagnosis (#2530).
- Eval: 460 passed, 2 failed, 3 skipped; two failures request absent hardcoded model aliases (#2530). Real embedding evaluation completed 1,379 STS-B pairs with Spearman 0.8485 / Pearson 0.8446; these are campaign measurements, not release baselines.

**Qualification remains open.** This campaign provides macOS 27 physical inference evidence only. It does not establish macOS 26 or physical iOS 26/27 inference, UI/migration qualification, updated deployment floors, or exact-release-candidate compatibility. Temporary build overrides and excluded/failed/skipped tests cannot be counted as a stock-build or full-suite pass. The new issues are linked into #2211 under its existing core/claim/companion boundaries.

**Comment by roryford** [comment]
Overnight platform evidence (18 September 2026): core PR #2536 remains **draft / held**, at reviewed head `44041b9982e83ad7c81b19785c7804f39e3c0022`. Independent review is SHIP for the source; that is not permission to skip the coordinated compatibility gates.

- The final full local profile passed with 7,273 reported tests and zero failures on macOS 27.0 (26A428), Xcode 27.0 (27A266a), Swift 6.4. Parallel XCTest reporting folds skips into the pass count.
- The actual iOS file-protection gate passed on both installed runtimes: iOS 26.5 (23F77) and iOS 27 **beta runtime 24A5380i**, each 7 executed / 2 explicitly skipped / zero failures. The latter used iPhone 18 Pro. The skips include the physical-hardware protection-class check; neither result is physical-device or OS27 GA-runtime qualification. Both xcresults are retained in the local evidence bundle.
- Advanced iOS build-for-testing passed. This is not a complete two-generation UI/consumer matrix or prior-MK-store migration qualification.
- Core/example floor changes, no-op trait removal and migration guidance are prepared. Companion minimums/runtime-CI alignment remain unapplied: automatic approval review rejected the companion changes as a breaking compatibility/service change requiring an explicit approval after the legacy-support impact. Shared-workflow prerequisites are prepared locally but could not be committed because the signing agent is unavailable. No merge or release is being claimed past either block.

Next dependency order remains coordinated companion/shared-workflow alignment, current-head compatibility canaries, then core ready/CI/queue; finally the full exact-release-candidate matrix and real prior-store/consumer qualification. Keep #2517 open.
